[general]
import = [
  "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[window]
opacity = 0.95
blur = true

[font]
size = 22.0
normal.family = "Maple Mono NF CN"
bold.family = "Maple Mono NF CN"
italic.family = "Maple Mono NF CN"
bold_italic.family = "Maple Mono NF CN"

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "On"

