-- Azulejo Brutalism: Ink on Glaze (light) / Glaze on Ink (dark), Cobalt primary, Ochre as the one highlight.
-- Follows `background`, so `:set background=dark|light` (or the terminal's appearance) switches mode.

local palettes = {
  light = {
    bg = "#F3F0E8", -- glaze
    bg_alt = "#E8E4D9", -- sidebars, floats, cursorline
    surface = "#DEDAD0",
    fg = "#0C1030", -- ink
    fg_dim = "#3D4163",
    muted = "#5A5E78",
    faint = "#8A8DA3",
    grout = "#0C1030",
    primary = "#1E2A9E", -- cobalt
    on_primary = "#F3F0E8",
    wash = "#9FB2E4",
    wash_tile = "#D6DAE7",
    ochre = "#D49A1A",
    yellow = "#8F6200",
    red = "#B03A2E",
    green = "#2F6B3A",
    purple = "#6B2E80",
    teal = "#1D6E7E",
    add_bg = "#DCE6D6",
    del_bg = "#F0D6CF",
    change_bg = "#DDE2EF",
    ansi = {
      "#0C1030", "#B03A2E", "#2F6B3A", "#8F6200", "#1E2A9E", "#6B2E80", "#1D6E7E", "#D8D4C8",
      "#5A5E78", "#C8513F", "#3E8A4C", "#B07A0C", "#3A48C4", "#8A48A0", "#2A8C9E", "#E8E4D9",
    },
  },
  dark = {
    bg = "#0C1030", -- ink
    bg_alt = "#10154A",
    surface = "#1A2150",
    fg = "#F3F0E8", -- glaze
    fg_dim = "#C9CBE0",
    muted = "#8A8FB5",
    faint = "#5A5F88",
    grout = "#1E2A9E",
    primary = "#9FB2E4", -- wash stands in for cobalt, which vanishes on ink
    on_primary = "#0C1030",
    wash = "#1E2A9E",
    wash_tile = "#1E2A9E",
    ochre = "#D49A1A",
    yellow = "#D49A1A",
    red = "#E0705A",
    green = "#7CBF7A",
    purple = "#C08AD6",
    teal = "#6FC3CF",
    add_bg = "#16304A",
    del_bg = "#3A1A3A",
    change_bg = "#1A2466",
    ansi = {
      "#141B6B", "#E0705A", "#7CBF7A", "#D49A1A", "#9FB2E4", "#C08AD6", "#6FC3CF", "#D8D4C8",
      "#6E7399", "#F08C78", "#98D496", "#E8B84A", "#C3CFF2", "#D6A8E6", "#94D8E2", "#F3F0E8",
    },
  },
}

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "azulejo-brutalism"
vim.o.termguicolors = true

local c = palettes[vim.o.background] or palettes.dark

for i, color in ipairs(c.ansi) do
  vim.g["terminal_color_" .. (i - 1)] = color
end

local groups = {
  -- Editor
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { link = "Normal" },
  NormalFloat = { fg = c.fg, bg = c.bg_alt },
  FloatBorder = { fg = c.grout, bg = c.bg_alt },
  FloatTitle = { fg = c.primary, bg = c.bg_alt, bold = true },
  WinSeparator = { fg = c.grout },
  VertSplit = { link = "WinSeparator" },
  Cursor = { fg = c.bg, bg = c.ochre },
  CursorLine = { bg = c.bg_alt },
  CursorColumn = { link = "CursorLine" },
  ColorColumn = { bg = c.bg_alt },
  LineNr = { fg = c.faint },
  CursorLineNr = { fg = c.ochre, bold = true },
  SignColumn = { bg = c.bg },
  FoldColumn = { fg = c.faint },
  Folded = { fg = c.muted, bg = c.bg_alt },
  EndOfBuffer = { fg = c.bg },
  NonText = { fg = c.faint },
  Whitespace = { fg = c.surface },
  SpecialKey = { fg = c.faint },
  Conceal = { fg = c.muted },
  Visual = { bg = c.wash },
  VisualNOS = { link = "Visual" },
  Search = { fg = "#0C1030", bg = c.ochre },
  IncSearch = { fg = c.on_primary, bg = c.primary, bold = true },
  CurSearch = { link = "IncSearch" },
  Substitute = { link = "IncSearch" },
  MatchParen = { fg = c.primary, bold = true, underline = true },
  Directory = { fg = c.primary, bold = true },
  Title = { fg = c.primary, bold = true },
  Question = { fg = c.primary },
  MoreMsg = { fg = c.primary },
  ModeMsg = { fg = c.fg, bold = true },
  ErrorMsg = { fg = c.red, bold = true },
  WarningMsg = { fg = c.yellow },
  StatusLine = { fg = c.fg, bg = c.bg_alt },
  StatusLineNC = { fg = c.muted, bg = c.bg_alt },
  TabLine = { fg = c.muted, bg = c.bg_alt },
  TabLineFill = { bg = c.bg_alt },
  TabLineSel = { fg = c.on_primary, bg = c.primary, bold = true },
  WinBar = { fg = c.fg, bold = true },
  WinBarNC = { fg = c.muted },
  Pmenu = { fg = c.fg, bg = c.bg_alt },
  PmenuSel = { fg = c.on_primary, bg = c.primary, bold = true },
  PmenuSbar = { bg = c.surface },
  PmenuThumb = { bg = c.muted },
  PmenuKind = { fg = c.purple, bg = c.bg_alt },
  PmenuExtra = { fg = c.muted, bg = c.bg_alt },
  WildMenu = { link = "PmenuSel" },
  QuickFixLine = { bg = c.wash_tile, bold = true },
  SpellBad = { sp = c.red, undercurl = true },
  SpellCap = { sp = c.yellow, undercurl = true },
  SpellRare = { sp = c.purple, undercurl = true },
  SpellLocal = { sp = c.teal, undercurl = true },

  -- Syntax: few colours; keywords carry the Cobalt, strings/numbers/types take the pigments.
  Comment = { fg = c.muted, italic = true },
  Constant = { fg = c.yellow },
  String = { fg = c.green },
  Character = { link = "String" },
  Number = { fg = c.yellow },
  Boolean = { fg = c.yellow, bold = true },
  Float = { link = "Number" },
  Identifier = { fg = c.fg },
  Function = { fg = c.fg, bold = true },
  Statement = { fg = c.primary, bold = true },
  Keyword = { fg = c.primary, bold = true },
  Conditional = { link = "Keyword" },
  Repeat = { link = "Keyword" },
  Label = { link = "Keyword" },
  Exception = { link = "Keyword" },
  Operator = { fg = c.fg_dim },
  PreProc = { fg = c.purple },
  Include = { fg = c.primary, bold = true },
  Type = { fg = c.purple },
  StorageClass = { link = "Keyword" },
  Structure = { link = "Type" },
  Typedef = { link = "Type" },
  Special = { fg = c.teal },
  SpecialChar = { fg = c.teal },
  Delimiter = { fg = c.muted },
  SpecialComment = { fg = c.muted, bold = true },
  Tag = { fg = c.primary },
  Underlined = { underline = true },
  Error = { fg = c.red },
  Todo = { fg = "#0C1030", bg = c.ochre, bold = true },

  -- Treesitter
  ["@variable"] = { fg = c.fg },
  ["@variable.builtin"] = { fg = c.teal, italic = true },
  ["@variable.parameter"] = { fg = c.fg_dim },
  ["@variable.member"] = { fg = c.fg },
  ["@property"] = { fg = c.fg },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { fg = c.yellow, bold = true },
  ["@module"] = { fg = c.purple },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = c.teal },
  ["@string.regexp"] = { fg = c.teal },
  ["@string.special.url"] = { fg = c.primary, underline = true },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { fg = c.teal, bold = true },
  ["@function.call"] = { fg = c.fg },
  ["@function.method.call"] = { fg = c.fg },
  ["@constructor"] = { fg = c.purple, bold = true },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.return"] = { fg = c.primary, bold = true },
  ["@keyword.import"] = { link = "Include" },
  ["@operator"] = { link = "Operator" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = c.purple, italic = true },
  ["@attribute"] = { fg = c.teal },
  ["@punctuation"] = { link = "Delimiter" },
  ["@punctuation.special"] = { fg = c.teal },
  ["@comment"] = { link = "Comment" },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.note"] = { fg = c.on_primary, bg = c.primary, bold = true },
  ["@comment.warning"] = { fg = "#0C1030", bg = c.ochre, bold = true },
  ["@comment.error"] = { fg = c.bg, bg = c.red, bold = true },
  ["@tag"] = { fg = c.primary, bold = true },
  ["@tag.attribute"] = { fg = c.purple },
  ["@tag.delimiter"] = { link = "Delimiter" },
  ["@markup.heading"] = { fg = c.primary, bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.link"] = { fg = c.primary },
  ["@markup.link.url"] = { fg = c.primary, underline = true },
  ["@markup.raw"] = { fg = c.green },
  ["@markup.list"] = { fg = c.primary },
  ["@markup.quote"] = { fg = c.fg_dim, italic = true },
  ["@diff.plus"] = { fg = c.green },
  ["@diff.minus"] = { fg = c.red },
  ["@diff.delta"] = { fg = c.primary },

  -- LSP
  ["@lsp.type.namespace"] = { link = "@module" },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.mod.deprecated"] = { strikethrough = true },
  LspReferenceText = { bg = c.wash_tile },
  LspReferenceRead = { link = "LspReferenceText" },
  LspReferenceWrite = { link = "LspReferenceText" },
  LspInlayHint = { fg = c.faint, italic = true },
  LspSignatureActiveParameter = { fg = c.ochre, bold = true },

  -- Diagnostics: no pastel, ochre for warnings
  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.primary },
  DiagnosticHint = { fg = c.teal },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.primary, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.teal, undercurl = true },
  DiagnosticUnnecessary = { fg = c.faint },

  -- Diff / git
  DiffAdd = { bg = c.add_bg },
  DiffDelete = { bg = c.del_bg },
  DiffChange = { bg = c.change_bg },
  DiffText = { bg = c.wash, bold = true },
  Added = { fg = c.green },
  Removed = { fg = c.red },
  Changed = { fg = c.primary },
  GitSignsAdd = { fg = c.green },
  GitSignsChange = { fg = c.primary },
  GitSignsDelete = { fg = c.red },

  -- LazyVim plugins
  SnacksPicker = { link = "NormalFloat" },
  SnacksPickerBorder = { link = "FloatBorder" },
  SnacksPickerMatch = { fg = c.primary, bold = true },
  SnacksPickerDir = { fg = c.muted },
  SnacksIndent = { fg = c.surface },
  SnacksIndentScope = { fg = c.muted },
  SnacksDashboardHeader = { fg = c.primary, bold = true },
  SnacksDashboardKey = { fg = c.ochre, bold = true },
  SnacksDashboardDesc = { fg = c.fg },
  SnacksDashboardIcon = { fg = c.primary },
  SnacksDashboardFooter = { fg = c.muted },
  BlinkCmpMenu = { link = "Pmenu" },
  BlinkCmpMenuBorder = { link = "FloatBorder" },
  BlinkCmpMenuSelection = { link = "PmenuSel" },
  BlinkCmpLabelMatch = { fg = c.primary, bold = true },
  BlinkCmpKind = { fg = c.purple },
  BlinkCmpDoc = { link = "NormalFloat" },
  BlinkCmpDocBorder = { link = "FloatBorder" },
  CmpItemAbbrMatch = { fg = c.primary, bold = true },
  CmpItemKind = { fg = c.purple },
  WhichKey = { fg = c.ochre, bold = true },
  WhichKeyGroup = { fg = c.primary },
  WhichKeyDesc = { fg = c.fg },
  WhichKeySeparator = { fg = c.muted },
  WhichKeyNormal = { link = "NormalFloat" },
  TelescopeBorder = { link = "FloatBorder" },
  TelescopeSelection = { link = "PmenuSel" },
  TelescopeMatching = { fg = c.primary, bold = true },
  NeoTreeNormal = { fg = c.fg, bg = c.bg_alt },
  NeoTreeNormalNC = { link = "NeoTreeNormal" },
  NeoTreeDirectoryName = { fg = c.fg },
  NeoTreeDirectoryIcon = { fg = c.primary },
  NeoTreeRootName = { fg = c.primary, bold = true },
  NeoTreeGitModified = { fg = c.primary },
  NeoTreeGitUntracked = { fg = c.green },
  BufferLineFill = { bg = c.bg_alt },
  BufferLineBufferSelected = { fg = c.fg, bold = true },
  BufferLineIndicatorSelected = { fg = c.ochre },
  NoiceCmdlinePopupBorder = { link = "FloatBorder" },
  NoiceCmdlineIcon = { fg = c.primary },
  FlashLabel = { fg = "#0C1030", bg = c.ochre, bold = true },
  FlashMatch = { fg = c.primary, bg = c.wash_tile },
  FlashCurrent = { link = "IncSearch" },
  TroubleNormal = { link = "NormalFloat" },
  MiniIconsAzure = { fg = c.primary },
  MiniIconsBlue = { fg = c.primary },
  MiniIconsCyan = { fg = c.teal },
  MiniIconsGreen = { fg = c.green },
  MiniIconsGrey = { fg = c.muted },
  MiniIconsOrange = { fg = c.yellow },
  MiniIconsPurple = { fg = c.purple },
  MiniIconsRed = { fg = c.red },
  MiniIconsYellow = { fg = c.yellow },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

-- Re-apply when the background flips (e.g. Ghostty switching with macOS appearance).
vim.api.nvim_create_autocmd("OptionSet", {
  group = vim.api.nvim_create_augroup("AzulejoBrutalism", { clear = true }),
  pattern = "background",
  callback = function()
    if vim.g.colors_name == "azulejo-brutalism" then vim.cmd.colorscheme("azulejo-brutalism") end
  end,
})
