[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "kotlin"
auto-format = true
formatter = { command = "ktlint", args = ["--format", "--stdin"]}

