[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "kotlin"
auto-format = true
formatter = { command = "ktlint", args = ["--format", "--stdin"]}

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["pylsp","ruff"]
auto-format = true
